[package]
name = "cauemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modular-bitfield = "0.11.2"
sdl2 = { version = "0.35.2", features = ["ttf"] }
